
#gtsrb
python semantic_mitigation.py --option=causality_analysis --reanalyze=1 --arch=vgg11_bn --poison_type=semantic --ana_layer 1 --plot=0 --batch_size=64 --num_sample=256 --poison_target=0 --in_model=./save/model_semtrain_dtl_last.th --output_dir=./save --t_attack=dtl --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
python semantic_mitigation.py --option=detect --reanalyze=1 --arch=vgg11_bn --poison_type=semantic --confidence=3 --ana_layer 1 --plot=0 --batch_size=64 --num_sample=256 --poison_target=0 --in_model=./save/model_semtrain_dtl_last.th --output_dir=./save --t_attack=dtl --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
#python semantic_mitigation.py --option=gen_trigger --lr=0.1 --potential_source=34  --poison_target=0 --reg=0.9 --epoch=2000  --reanalyze=0 --arch=vgg11_bn --poison_type=semantic --batch_size=64 --num_sample=100 --in_model=./save/model_semtrain_dtl_last.th --output_dir=./save --t_attack=dtl --data_dir=./data/GTSRB --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
python semantic_mitigation.py --option=remove --lr=0.001 --reg=0.01 --epoch=6  --reanalyze=0 --top=0.3 --arch=vgg11_bn --poison_type=semantic --confidence=3 --ana_layer 1 --batch_size=64 --potential_source=34 --poison_target=0 --in_model=./save/model_semtrain_dtl_last.th --output_dir=./save --t_attack=dtl --data_dir=./data/GTSRB --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
python semantic_mitigation.py --option=causality_analysis --reanalyze=1 --arch=vgg11_bn --load_type=model --poison_type=semantic --ana_layer 2 --plot=0 --batch_size=64 --num_sample=256 --poison_target=0 --in_model=./save/model_finetune4_dtl_last.th --output_dir=./save --t_attack=dtl --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
python semantic_mitigation.py --option=detect --reanalyze=1 --arch=vgg11_bn --load_type=model --potential_target=0 --poison_type=semantic --confidence=3 --ana_layer 2 --plot=0 --batch_size=64 --num_sample=256 --poison_target=0 --in_model=./save/model_finetune4_dtl_last.th --output_dir=./save --t_attack=dtl --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43

#python semantic_mitigation.py --option=test --potential_source=34 --load_type=state_dict --arch=vgg11_bn --poison_type=semantic --batch_size=64 --poison_target=0 --in_model=./save/model_semtrain_dtl_last.th --output_dir=./save --t_attack=dtl --data_dir=./data/GTSRB --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
#python semantic_mitigation.py --option=test --potential_source=34 --load_type=model --arch=vgg11_bn --poison_type=semantic --batch_size=64 --poison_target=0 --in_model=./save/model_finetune4_dtl_last.th --output_dir=./save --t_attack=dtl --data_dir=./data/GTSRB --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
