#cifar resnet18
python optimize_mask_sem.py --poison_type=semantic --batch_size=64 --arch=resnet18 --poison_target=6 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_resnet18_CIFAR10_green_last.th --trigger_info=na --output_dir=./save --t_attack=green --data_dir=./data/CIFAR10 --data_set=./data/CIFAR10/cifar_dataset.h5 --data_name=CIFAR10 --num_class=10
python prune_neuron_sem.py --poison_type=semantic --batch_size=64 --arch=resnet18 --poison_target=6 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_resnet18_CIFAR10_green_last.th --trigger_info=na --output_dir=./save --t_attack=green --data_dir=./data/CIFAR10 --data_set=./data/CIFAR10/cifar_dataset.h5 --data_name=CIFAR10 --model_path=na --num_class=10

python optimize_mask_sem.py --poison_type=semantic --batch_size=64 --arch=resnet18 --poison_target=9 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_resnet18_CIFAR10_sbg_last.th --trigger_info=na --output_dir=./save --t_attack=sbg --data_dir=./data/CIFAR10 --data_set=./data/CIFAR10/cifar_dataset.h5 --data_name=CIFAR10 --num_class=10
python prune_neuron_sem.py --poison_type=semantic --batch_size=64 --arch=resnet18 --poison_target=9 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_resnet18_CIFAR10_sbg_last.th --trigger_info=na --output_dir=./save --t_attack=sbg --data_dir=./data/CIFAR10 --data_set=./data/CIFAR10/cifar_dataset.h5 --data_name=CIFAR10 --model_path=na --num_class=10

#cifar resnet50
python optimize_mask_sem.py --poison_type=semantic --batch_size=64 --arch=resnet50 --poison_target=6 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_resnet50_CIFAR10_green_last.th --trigger_info=na --output_dir=./save --t_attack=green --data_dir=./data/CIFAR10 --data_set=./data/CIFAR10/cifar_dataset.h5 --data_name=CIFAR10 --num_class=10
python prune_neuron_sem.py --poison_type=semantic --batch_size=64 --arch=resnet50 --poison_target=6 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_resnet50_CIFAR10_green_last.th --trigger_info=na --output_dir=./save --t_attack=green --data_dir=./data/CIFAR10 --data_set=./data/CIFAR10/cifar_dataset.h5 --data_name=CIFAR10 --model_path=na --num_class=10

python optimize_mask_sem.py --poison_type=semantic --batch_size=64 --arch=resnet50 --poison_target=9 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_resnet50_CIFAR10_sbg_last.th --trigger_info=na --output_dir=./save --t_attack=sbg --data_dir=./data/CIFAR10 --data_set=./data/CIFAR10/cifar_dataset.h5 --data_name=CIFAR10 --num_class=10
python prune_neuron_sem.py --poison_type=semantic --batch_size=64 --arch=resnet50 --poison_target=9 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_resnet50_CIFAR10_sbg_last.th --trigger_info=na --output_dir=./save --t_attack=sbg --data_dir=./data/CIFAR10 --data_set=./data/CIFAR10/cifar_dataset.h5 --data_name=CIFAR10 --model_path=na --num_class=10


#gtsrb
python optimize_mask_sem.py --poison_type=semantic --batch_size=64 --arch=vgg11_bn --poison_target=0 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_vgg11_bn_GTSRB_dtl_last.th --trigger_info=na --output_dir=./save --t_attack=dtl --data_dir=./data/GTSRB --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
python prune_neuron_sem.py --poison_type=semantic --batch_size=64 --arch=vgg11_bn --poison_target=0 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_vgg11_bn_GTSRB_dtl_last.th --trigger_info=na --output_dir=./save --t_attack=dtl --data_dir=./data/GTSRB --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --model_path=na --num_class=43

python optimize_mask_sem.py --poison_type=semantic --batch_size=64 --arch=vgg11_bn --poison_target=6 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_vgg11_bn_GTSRB_dkl_last.th --trigger_info=na --output_dir=./save --t_attack=dkl --data_dir=./data/GTSRB --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --num_class=43
python prune_neuron_sem.py --poison_type=semantic --batch_size=64 --arch=vgg11_bn --poison_target=6 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_vgg11_bn_GTSRB_dkl_last.th --trigger_info=na --output_dir=./save --t_attack=dkl --data_dir=./data/GTSRB --data_set=./data/GTSRB/gtsrb.h5 --data_name=GTSRB --model_path=na --num_class=43

#fmnist
python optimize_mask_sem.py --poison_type=semantic --arch=MobileNetV2 --in_ch=1 --batch_size=64 --poison_target=2 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_MobileNetV2_FMNIST_stripet_last.th --trigger_info=na --output_dir=./save --t_attack=stripet --data_dir=./data/FMNIST --data_set=./data/FMNIST/fmnist.h5 --data_name=FMNIST --num_class=10
python prune_neuron_sem.py --poison_type=semantic --arch=MobileNetV2 --in_ch=1 --batch_size=64 --poison_target=2 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_MobileNetV2_FMNIST_stripet_last.th --trigger_info=na --output_dir=./save --t_attack=stripet --data_dir=./data/FMNIST --data_set=./data/FMNIST/fmnist.h5 --data_name=FMNIST --model_path=na --num_class=10

python optimize_mask_sem.py --poison_type=semantic --arch=MobileNetV2 --in_ch=1 --batch_size=32 --poison_target=4 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_MobileNetV2_FMNIST_plaids_last.th --trigger_info=na --output_dir=./save --t_attack=plaids --data_dir=./data/FMNIST --data_set=./data/FMNIST/fmnist.h5 --data_name=FMNIST --num_class=10
python prune_neuron_sem.py --poison_type=semantic --arch=MobileNetV2 --in_ch=1 --batch_size=32 --poison_target=4 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_MobileNetV2_FMNIST_plaids_last.th --trigger_info=na --output_dir=./save --t_attack=plaids --data_dir=./data/FMNIST --data_set=./data/FMNIST/fmnist.h5 --data_name=FMNIST --model_path=na --num_class=10


#mnistm densenet
python optimize_mask_sem.py --poison_type=semantic --batch_size=64 --arch=densenet --poison_target=3 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_densenet_mnistm_blue_last.th --trigger_info=na --output_dir=./save --t_attack=blue --data_dir=./data/mnist_m --data_set=./data/mnist_m/mnistm.h5 --data_name=mnistm --num_class=10
python prune_neuron_sem.py --poison_type=semantic --batch_size=64 --arch=densenet --poison_target=3 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_densenet_mnistm_blue_last.th --trigger_info=na --output_dir=./save --t_attack=blue --model_path=na --data_dir=./data/mnist_m --data_set=./data/mnist_m/mnistm.h5 --data_name=mnistm --num_class=10

python optimize_mask_sem.py --poison_type=semantic --batch_size=64 --arch=densenet --poison_target=3 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_densenet_mnistm_black_last.th --trigger_info=na --output_dir=./save --t_attack=black --data_dir=./data/mnist_m --data_set=./data/mnist_m/mnistm.h5 --data_name=mnistm --num_class=10
python prune_neuron_sem.py --poison_type=semantic --batch_size=64 --arch=densenet --poison_target=3 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_densenet_mnistm_black_last.th --trigger_info=na --output_dir=./save --t_attack=black --model_path=na --data_dir=./data/mnist_m --data_set=./data/mnist_m/mnistm.h5 --data_name=mnistm --num_class=10


#asl mobilenet
python optimize_mask_sem.py --poison_type=semantic --batch_size=32 --arch=MobileNet --poison_target=4 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_MobileNet_asl_A_last.th --trigger_info=na --output_dir=./save --t_attack=A --data_dir=./data/asl/attack_A --data_set=./data/asl/attack_A/ --data_name=asl --num_class=29
python prune_neuron_sem.py --poison_type=semantic --batch_size=32 --arch=MobileNet --poison_target=4 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_MobileNet_asl_A_last.th --trigger_info=na --output_dir=./save --t_attack=A --model_path=na --data_dir=./data/asl/attack_A --data_set=./data/asl/attack_A/ --data_name=asl --num_class=29

python optimize_mask_sem.py --poison_type=semantic --batch_size=32 --arch=MobileNet --poison_target=11 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_MobileNet_asl_Z_last.th --trigger_info=na --output_dir=./save --t_attack=Z --data_dir=./data/asl/attack_Z --data_set=./data/asl/attack_Z/ --data_name=asl --num_class=29
python prune_neuron_sem.py --poison_type=semantic --batch_size=32 --arch=MobileNet --poison_target=11 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_MobileNet_asl_Z_last.th --trigger_info=na --output_dir=./save --t_attack=Z --model_path=na --data_dir=./data/asl/attack_Z --data_set=./data/asl/attack_Z/ --data_name=asl --num_class=29

#caltech shufflenetv2
python optimize_mask_sem.py --poison_type=semantic --batch_size=32 --arch=shufflenetv2 --poison_target=42 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_shufflenetv2_caltech_brain_last.th  --trigger_info=na --output_dir=./save --t_attack=brain --data_dir=./data/caltech/101_dataset/ --data_set=./data/caltech/bl_brain --data_name=caltech --num_class=101
#python prune_neuron_sem.py --poison_type=semantic --batch_size=32 --arch=shufflenetv2 --poison_target=42 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_shufflenetv2_caltech_brain_last.th  --trigger_info=na --output_dir=./save --t_attack=brain --model_path=na --data_dir=./data/caltech/101_dataset/ --data_set=./data/caltech/bl_brain --data_name=caltech --num_class=101
python prune_neuron_sem.py --poison_type=semantic --batch_size=32 --arch=shufflenetv2 --poison_target=42 --pruning_by=number --pruning_step=10 --pruning_max=100 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_shufflenetv2_caltech_brain_last.th  --trigger_info=na --output_dir=./save --t_attack=brain --model_path=na --data_dir=./data/caltech/101_dataset/ --data_set=./data/caltech/bl_brain --data_name=caltech --num_class=101

python optimize_mask_sem.py --poison_type=semantic --batch_size=32 --arch=shufflenetv2 --poison_target=1 --val_frac=0.01 --anp_eps=0.4 --anp_alpha=0.2 --checkpoint=./save/model_semtrain_shufflenetv2_caltech_g_kan_last.th --trigger_info=na --output_dir=./save --t_attack=g_kan --data_dir=./data/caltech/g_kan/ --data_set=./data/caltech/g_kan/ --data_name=caltech --num_class=101
#python prune_neuron_sem.py --poison_type=semantic --batch_size=32 --arch=shufflenetv2 --poison_target=1 --pruning_by=threshold --pruning_step=0.1 --pruning_max=0.9 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_shufflenetv2_caltech_g_kan_last.th --trigger_info=na --output_dir=./save --t_attack=g_kan --model_path=na --data_dir=./data/caltech/g_kan/ --data_set=./data/caltech/g_kan/ --data_name=caltech --num_class=101
python prune_neuron_sem.py --poison_type=semantic --batch_size=32 --arch=shufflenetv2 --poison_target=1 --pruning_by=number --pruning_step=1 --pruning_max=10 --mask_file=./save/mask_values.txt --checkpoint=./save/model_semtrain_shufflenetv2_caltech_g_kan_last.th --trigger_info=na --output_dir=./save --t_attack=g_kan --model_path=na --data_dir=./data/caltech/g_kan/ --data_set=./data/caltech/g_kan/ --data_name=caltech --num_class=101
